export const DISPLAY_PRODUCTS = 'DISPLAY_PRODUCTS'
export const ADD_TO_CART = 'ADD_TO_CART'
export const ADD_NOTIFICATION_QUEUE = 'ADD_NOTIFICATION_QUEUE'
export const SHOW_NOTIFICATIONS = 'SHOW_NOTIFICATIONS'
export const NOTIFICATION_COMPLETE = 'NOTIFICATION_COMPLETE'
export const REMOVE_ITEM="REMOVE_ITEM";
export const DECREMENT_QUANTITY="DECREMENT_QUANTITY";
